version: '3'

networks:
    internal:

services:
    goproxy:
        build:
          context: ./
          dockerfile: Dockerfile
        container_name: go-proxy
        volumes:
          - ./config:/app/config
        ports:
          - "12345:12345"
        networks:
          - internal
